name: installing dependancies using cache

on: workflow_dispatch

jobs:
  caching:
    runs-on: ubuntu-latest
    steps:

      - name: uses cache for apt package
        uses: actions/cache@v4
        with:
          path: ~/var/cache/apt
          key: ${{ runner.os }}-apt-cache

      - name: install docker
        run: |
             sudo apt-get update
