name: call a workflow

on:
  push:
    branches: [ main ]

jobs:

  call-a-workflow:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: 'my-web-app'
      environment: 'prod'
    secrets:
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}

  print-version:
    runs-on: ubuntu-latest
    needs: call-a-workflow
    steps:
        - name: print build version
          run: echo "build version is ${{ needs.call-a-workflow.outputs.build_version }}"
    
