name: call a workflow

on:
  push:
    branches: [ main ]

jobs:

  call-a-workflow:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: 'my-web-app'
      environment: 'prod'
    secrets:
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
      