# this is name of workflow
name: CICD

# on manual click

on:
  workflow_dispatch:
    inputs:
      environment:
        default: 'dev'
        type: choice
        required: true
        options:
          - dev
          - test
          - prod
        
    
jobs:

  code :
    runs-on: ubuntu-latest
    steps:
      - name: copy the code from github
        run: echo "code copied"
        
  buid :
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: build a docker image
        run: echo "docker conatiner created"
        
  test :
    runs-on: ubuntu-latest
    needs: buid
    steps:
      - name: test the code
        run: echo "testing the code"
        
  deploy :
    if: inputs.environment== 'dev'
    runs-on: ubuntu-latest
    needs: 
      - buid
      - test
    steps:
      - name: deployed the app
        run: echo "app is runing"
