name: DevSecOps Pipeline

on: 
    workflow_dispatch:

jobs:

  code-scan:
    uses: ./.github/workflows/code-scan.yml

  secret-scan:
    uses: ./.github/workflows/secretes-scan.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  docker-lint:
    uses: ./.github/workflows/docker-lint.yml

  build-push:
    needs: [code-scan, secret-scan ,dependency-scan , docker-lint ]
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit

  image-scan:
    needs: [ build-push ]
    uses: ./.github/workflows/image-scan.yml

#   deploy-to-server:
#     uses: ./.github/workflow/deploy-to-server.yml

