name : docker build and push 

on:
  push:
    branches: [ main ]
    paths: 
      - '.github/workflows/docker-push-build.yml'
      - 'Dockerfile'
      - 'app.py'
      - 'requirements.txt' 
      - 'templates/**' 
  

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: login to docker hub 
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USER }}/pyton-flask-app-github-actions:latest
                ${{ vars.DOCKERHUB_USER }}/pyton-flask-app-github-actions:${{ github.sha }}

      