name : hello

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print hellow from github actions
        run: echo "hellow from github actions"

      - name: print the current date and time
        run:  date

      - name: Print the name of the branch that triggered the run
        run: "The branch that triggered this run is ${{ github.ref }}"

      - name: List the files in the repo
        run: ls -lart

      - name: Print the runner's operating system
        run:  "The runner is running on ${{ runner.os }}"

    
    


