name: hellow

# runs on push to main branch but only when chamges to html file occur 

#on:
#  push: 
#    branches: [main]
#   paths:
#      - '**.html'

# on:
#   workflow_dispatch:

on:
  schedule:
    - cron: '16 18 * * *' # every 18:16 minutes

#on: workflow_dispatch

jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hellow to user
        run : echo "hellow dosto"

      - name: say hellow to username
        run : echo "hellow $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: show the version of docker
        run: docker --version 

      - name: show the version of python
        run: python --version
