name: secrets-test

on: workflow_dispatch

jobs:
  secret-var-test:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout code
        uses: actions/checkout@v4

      - name: print the secrets
        
        # pass secret to step as env varaiable
        env:
          my_secret: ${{ secrets.MY_SECRET_MESSAGE }}
       
        run: echo "my secret msg is $my_secret "
        #run: echo "print your secret msg ${{ secrets.MY_SECRET_MESSAGE }}"


