name: secrets-test

on: workflow_dispatch

jobs:
  secret-var-test:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout code
        uses: actions/checkout@v4

      - name: print the secrets
        run: echo "print your secret msg ${{ secrets.MY_SECRET_MESSAGE }}"
