name: self-hoster-runner

on: workflow_dispatch
  

jobs:
  self_host:
    runs-on: self-hosted
    steps:
      - name: print the hostname of machine
        run: hostname

      - name: print the working directory
        run: pwd 

      - name: create a file 
        run: touch hellow.txt
